
  try:
      print(x)
  except:
      print("something went wrong")
  finally:
      print("the 'try exept' is finished")

or


print(x)
  except: NameError
      print("veriable x is not defined")
finally:
      print("everything went wrong")

x = -1

if x < 0:



