
  try:
      print(x)
  except:
      print("the 'try exept' is finished")
